apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ include "test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      name: web
      targetPort: 9090
  selector:
    app: {{ .Release.Name }}